use_frameworks!

target 'Mylibrary_Example' do
  pod 'Mylibrary', :path => '../'

  target 'Mylibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
